Repository ljhpaul/cardgarden, pull requests merged in 2025-07, with the labels that each got.

#112 feat: 소셜 로그인/회원가입 초기세팅 완료
  pom.xml
  src/main/java/com/cardgarden/project/config/OAuth2ClientConfig.java
  src/main/java/com/cardgarden/project/config/SecurityConfig.java
  src/main/java/com/cardgarden/project/controller/auth/OAuthController.java
  src/main/java/com/cardgarden/project/controller/user/JoinController.java
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#114 fix: 로그인 오류 해결
  src/main/java/com/cardgarden/project/config/OAuth2SuccessHandler.java
  src/main/java/com/cardgarden/project/config/SecurityConfig.java
  src/main/java/com/cardgarden/project/controller/user/LoginController.java
  src/main/java/com/cardgarden/project/model/auth/CustomOAuth2UserService.java
  src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: enhancement

#123 feat: 구글 로그인/회원가입 완료
  src/main/java/com/cardgarden/project/controller/user/JoinController.java
  src/main/webapp/WEB-INF/views/join/inputInfo.jsp
Labels: enhancement

#131 feat: 관리자페이지 시각화 구현
  src/main/java/com/cardgarden/project/controller/AdminMetaBaseController.java
  src/main/java/com/cardgarden/project/controller/recommend/UserPatternBenefitController.java
  src/main/webapp/WEB-INF/views/admin/metabase.jsp
  src/main/webapp/WEB-INF/views/recommend/ai.jsp
Labels: enhancement

#135 feat: 로그인 최신화
  src/main/java/com/cardgarden/project/config/OAuth2ClientConfig.java
  src/main/java/com/cardgarden/project/config/OAuth2SuccessHandler.java
  src/main/java/com/cardgarden/project/config/SecurityConfig.java
  src/main/java/com/cardgarden/project/controller/user/JoinController.java
  src/main/java/com/cardgarden/project/model/auth/CustomOAuth2UserService.java
  src/main/webapp/WEB-INF/views/join/inputInfo.jsp
Labels: enhancement

#136 feat & fix: 관리자 시각화 구현 및 세부 기능 조정
  python/code/.ipynb_checkpoints/card_recommend_total-checkpoint.py
  python/code/card_recommend_total.py
  python/data/.ipynb_checkpoints/card_detail_recommend-checkpoint.py
  python/data/.ipynb_checkpoints/card_recommend-checkpoint.py
  python/data/.ipynb_checkpoints/card_recommend_cosine-checkpoint.py
  python/data/card_detail_recommend.py
  python/data/card_recommend.py
  python/data/card_recommend_cosine.py
  src/main/webapp/WEB-INF/views/mypage/sidebar.jsp
  src/main/webapp/WEB-INF/views/recommend/ai.jsp
Labels: bug, enhancement

#138 feat: 로그인 성공 후 리다이렉트 분기
  src/main/java/com/cardgarden/project/controller/event/AttendanceController.java
  src/main/java/com/cardgarden/project/controller/user/LoginController.java
  src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: enhancement

#142 fix: 카드 디테일 좋아요 경로 수정
  src/main/java/com/cardgarden/project/controller/card/like/CardLikeController.java
  src/main/java/com/cardgarden/project/controller/recommend/UserPatternBenefitController.java
  src/main/webapp/WEB-INF/views/card/cardDetail.jsp
  src/main/webapp/WEB-INF/views/recommend/ai.jsp
Labels: bug

#145 feat: gitignore 하나 추가
  .gitignore
Labels: enhancement

#148 fix: 커스텀카드 선택시 요소 삭제 버그 수정
  src/main/java/com/cardgarden/project/config/OAuth2ClientConfig.java
  src/main/java/com/cardgarden/project/config/OAuth2SuccessHandler.java
  src/main/java/com/cardgarden/project/config/SecurityConfig.java
  src/main/java/com/cardgarden/project/controller/user/JoinController.java
  src/main/java/com/cardgarden/project/controller/user/UserController.java
  src/main/java/com/cardgarden/project/model/auth/CustomOAuth2UserService.java
  src/main/webapp/WEB-INF/views/custom/makeSticker.jsp
  src/main/webapp/WEB-INF/views/join/inputInfo.jsp
  src/main/webapp/resources/images/custom/customcard/2_test1.png
  src/main/webapp/resources/images/custom/customcard/2_곰돌이teddy123.png
Labels: bug

#150 fix: card detail ai 로그인창 연결
  src/main/java/com/cardgarden/project/controller/card/pattern/AiConsumpatternController.java
  src/main/java/com/cardgarden/project/controller/recommend/RecommendAIController.java
  src/main/webapp/WEB-INF/views/card/cardDetail.jsp
Labels: bug

#155 feat: 로그인/회원가입 로직 오류 개선
  src/main/java/com/cardgarden/project/config/OAuth2SuccessHandler.java
  src/main/java/com/cardgarden/project/controller/auth/MailAuthController.java
  src/main/java/com/cardgarden/project/controller/user/JoinController.java
  src/main/resources/sql/ddl/schema.sql
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/images/custom/customcard/5027_adsf.png
  src/main/webapp/resources/images/custom/customcard/5027_asdf.png
Labels: enhancement

#157 fix: 로그인후 좋아요창 연결 오류 수정
  src/main/java/com/cardgarden/project/controller/event/AttendanceController.java
  src/main/java/com/cardgarden/project/controller/user/UserController.java
Labels: enhancement

#160 style: ai 추천 성공시 멘트 변경 및 title 수정
  python/code/card_recommend_total.py
  src/main/java/com/cardgarden/project/controller/card/detail/CardDetailController.java
  src/main/webapp/WEB-INF/views/card/cardDetail.jsp
  src/main/webapp/WEB-INF/views/recommend/ai.jsp
  src/main/webapp/WEB-INF/views/recommend/aiPattern.jsp
  src/main/webapp/WEB-INF/views/recommend/aiResult.jsp
  src/main/webapp/resources/images/custom/customcard/5008_경민이가시킴1.png
  src/main/webapp/resources/images/custom/customcard/5008_정헌이가시킴.png
  src/main/webapp/resources/images/custom/customcard/5008_정헌이가시킴2.png
  src/main/webapp/resources/images/custom/customcard/5008_정헌이가시킴3.png
  src/main/webapp/resources/images/custom/customcard/5008_정헌이가시킴4.png
  src/main/webapp/resources/images/custom/customcard/5008_정헌이가시킴5.png
  src/main/webapp/resources/images/custom/customcard/5008_정헌이가시킴6.png
  src/main/webapp/resources/images/custom/customcard/5008_정헌이가시킴7.png
Labels: bug

#163 fix: 세션 로그인 로고 오류 수정
  src/main/java/com/cardgarden/project/config/OAuth2SuccessHandler.java
Labels: enhancement

#170 fix: card detail ai loading창 변경
  python/code/.ipynb_checkpoints/card_recommend_total-checkpoint.py
  python/code/card_recommend_total.py
  src/main/java/com/cardgarden/project/controller/card/detail/CardDetailController.java
  src/main/java/com/cardgarden/project/controller/recommend/RecommendAIController.java
  src/main/java/com/cardgarden/project/controller/user/LoginController.java
  src/main/java/com/cardgarden/project/model/cardDetail/CardDAOInterface.java
  src/main/java/com/cardgarden/project/model/cardDetail/CardDAOMybatis.java
  src/main/java/com/cardgarden/project/model/cardDetail/CardService.java
  src/main/resources/mybatis/mappers/benefitDetailMapper.xml
  src/main/webapp/WEB-INF/views/card/cardDetail.jsp
  src/main/webapp/WEB-INF/views/recommend/ai.jsp
  src/main/webapp/resources/css/cardDetail.css
Labels: bug

#176 fix: 전월실적 금액 오류
  src/main/webapp/WEB-INF/views/card/cardDetail.jsp
Labels: bug

#178 fix: 카드 디테일 줄바꿈 수정
  src/main/java/com/cardgarden/project/model/cardDetail/CardDetailDTO.java
  src/main/webapp/WEB-INF/views/card/cardDetail.jsp
Labels: bug

#184 feat: 비밀번호 재설정 개선
  src/main/webapp/WEB-INF/views/login/findPwdReset.jsp
Labels: enhancement

#191 style: ai 추천 margin 변경
  src/main/webapp/WEB-INF/views/recommend/ai.jsp
Labels: bug

#196 fix: 혜택 계산기 url 충돌 해결
  python/code/card_recommend_total.py
  src/main/webapp/WEB-INF/views/recommend/insertUserConsumptionPattern.jsp
Labels: bug

#198 fix: 혜택 계산기 비로그인일떄도 가능하게 수정
  src/main/java/com/cardgarden/project/controller/card/detail/CardDetailController.java
Labels: bug

#210 fix: card 대문자 수정
  src/main/resources/mybatis/mappers/cardRankMapper.xml
Labels: bug

#213 fix: python 배포 준비 완료
  python/code/card_recommend_total.py
  python/code/requirements.txt
Labels: bug

#214 fix: ai 시간 조절
  python/code/card_recommend_total.py
Labels: bug

#215 fix: python version 0.1 추가
  python/code/card_recommend_total_v0.1.py
Labels: bug
